// Code generated by cmd/techstackgen; DO NOT EDIT.

package techstack

type Package struct {
	Name string
	URL  string
}

var packages = []Package{
	{Name: "genqlient", URL: "https://github.com/Khan/genqlient"},
	{Name: "templ", URL: "https://github.com/a-h/templ"},
	{Name: "chroma", URL: "https://github.com/alecthomas/chroma"},
	{Name: "markdown", URL: "https://github.com/gomarkdown/markdown"},
	{Name: "datastar-go", URL: "https://github.com/starfederation/datastar-go"},
}

func Packages() []Package {
	copied := make([]Package, len(packages))
	copy(copied, packages)
	return copied
}
