// Code generated by internal/cmd/techstackgen; DO NOT EDIT.

package techstack

type Package struct {
	Name string
	URL  string
}

var packages = []Package{
	{Name: "github.com/Khan/genqlient", URL: "https://pkg.go.dev/github.com/Khan/genqlient"},
	{Name: "github.com/a-h/templ", URL: "https://pkg.go.dev/github.com/a-h/templ"},
	{Name: "github.com/alecthomas/chroma/v2", URL: "https://pkg.go.dev/github.com/alecthomas/chroma/v2"},
	{Name: "github.com/gomarkdown/markdown", URL: "https://pkg.go.dev/github.com/gomarkdown/markdown"},
	{Name: "github.com/starfederation/datastar-go", URL: "https://pkg.go.dev/github.com/starfederation/datastar-go"},
	{Name: "golang.org/x/mod", URL: "https://pkg.go.dev/golang.org/x/mod"},
}

func Packages() []Package {
	copied := make([]Package, len(packages))
	copy(copied, packages)
	return copied
}
