version: "3"

env:
  GOCACHE: /tmp/go-cache
  GOMODCACHE: /tmp/go-modcache
  GOLANGCI_LINT_CACHE: /tmp/golangci-lint-cache

tasks:
  go:gen:
    desc: Run Go code generation
    cmds:
      - go generate ./internal/gql
      - go generate ./internal/web
      - go run ./cmd/techstackgen -in go.mod -out internal/techstack/generated.go

  go:gen:code-diff:
    desc: Verify generated outputs are committed
    cmds:
      - |
        set -euo pipefail
        templ_files="$(find internal/web -type f -name '*_templ.go' | sort)"
        git diff --exit-code -- go.mod go.sum internal/gql/generated.go internal/techstack/generated.go $templ_files

  go:gen:check:
    desc: Non-mutating generator freshness check
    cmds:
      - |
        set -euo pipefail
        templ_files="$(find internal/web -type f -name '*_templ.go' | sort)"
        files="go.mod go.sum internal/gql/generated.go internal/techstack/generated.go $templ_files"
        tmpdir="$(mktemp -d)"

        cleanup() {
          for f in $files; do
            cp "$tmpdir/$f" "$f"
          done
          rm -rf "$tmpdir"
        }

        for f in $files; do
          mkdir -p "$tmpdir/$(dirname "$f")"
          cp "$f" "$tmpdir/$f"
        done

        trap cleanup EXIT

        task go:gen
        if ! git diff --quiet -- $files; then
          echo "generated code is out of date; run 'task gen'"
          exit 1
        fi

  go:fmt:
    desc: Format Go sources
    cmds:
      - |
        set -euo pipefail
        files="$(find . -type f -name '*.go' -not -path './vendor/*')"
        if [ -n "$files" ]; then
          gofmt -w $files
        fi

  go:lint:
    desc: Run golangci-lint for all Go packages
    cmds:
      - golangci-lint run ./...

  go:test:
    desc: Run Go tests for all packages
    cmds:
      - go test ./...

  gen:
    desc: Run all code generation
    cmds:
      - task: go:gen

  gen:check:
    desc: Check code generation freshness (non-mutating)
    cmds:
      - task: go:gen:check

  gen:code-diff:
    desc: CI fallback generation diff check
    cmds:
      - task: go:gen:code-diff

  fix:
    desc: Run auto-fixes
    cmds:
      - task: go:fmt

  validate:
    desc: Run project validation checks
    cmds:
      - task: go:lint

  test:
    desc: Run test suite
    deps:
      - validate
    cmds:
      - task: go:test
