// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package gql

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// AuthorBySlugAuthors includes the requested fields of the GraphQL type Authors.
type AuthorBySlugAuthors struct {
	Docs []AuthorBySlugAuthorsDocsAuthor `json:"docs"`
}

// GetDocs returns AuthorBySlugAuthors.Docs, and is useful for accessing the field via an interface.
func (v *AuthorBySlugAuthors) GetDocs() []AuthorBySlugAuthorsDocsAuthor { return v.Docs }

// AuthorBySlugAuthorsDocsAuthor includes the requested fields of the GraphQL type Author.
type AuthorBySlugAuthorsDocsAuthor struct {
	Id     string                                    `json:"id"`
	Name   *string                                   `json:"name"`
	Slug   string                                    `json:"slug"`
	Bio    *string                                   `json:"bio"`
	Avatar *AuthorBySlugAuthorsDocsAuthorAvatarMedia `json:"avatar"`
}

// GetId returns AuthorBySlugAuthorsDocsAuthor.Id, and is useful for accessing the field via an interface.
func (v *AuthorBySlugAuthorsDocsAuthor) GetId() string { return v.Id }

// GetName returns AuthorBySlugAuthorsDocsAuthor.Name, and is useful for accessing the field via an interface.
func (v *AuthorBySlugAuthorsDocsAuthor) GetName() *string { return v.Name }

// GetSlug returns AuthorBySlugAuthorsDocsAuthor.Slug, and is useful for accessing the field via an interface.
func (v *AuthorBySlugAuthorsDocsAuthor) GetSlug() string { return v.Slug }

// GetBio returns AuthorBySlugAuthorsDocsAuthor.Bio, and is useful for accessing the field via an interface.
func (v *AuthorBySlugAuthorsDocsAuthor) GetBio() *string { return v.Bio }

// GetAvatar returns AuthorBySlugAuthorsDocsAuthor.Avatar, and is useful for accessing the field via an interface.
func (v *AuthorBySlugAuthorsDocsAuthor) GetAvatar() *AuthorBySlugAuthorsDocsAuthorAvatarMedia {
	return v.Avatar
}

// AuthorBySlugAuthorsDocsAuthorAvatarMedia includes the requested fields of the GraphQL type Media.
type AuthorBySlugAuthorsDocsAuthorAvatarMedia struct {
	Url    *string  `json:"url"`
	Alt    *string  `json:"alt"`
	Width  *float64 `json:"width"`
	Height *float64 `json:"height"`
}

// GetUrl returns AuthorBySlugAuthorsDocsAuthorAvatarMedia.Url, and is useful for accessing the field via an interface.
func (v *AuthorBySlugAuthorsDocsAuthorAvatarMedia) GetUrl() *string { return v.Url }

// GetAlt returns AuthorBySlugAuthorsDocsAuthorAvatarMedia.Alt, and is useful for accessing the field via an interface.
func (v *AuthorBySlugAuthorsDocsAuthorAvatarMedia) GetAlt() *string { return v.Alt }

// GetWidth returns AuthorBySlugAuthorsDocsAuthorAvatarMedia.Width, and is useful for accessing the field via an interface.
func (v *AuthorBySlugAuthorsDocsAuthorAvatarMedia) GetWidth() *float64 { return v.Width }

// GetHeight returns AuthorBySlugAuthorsDocsAuthorAvatarMedia.Height, and is useful for accessing the field via an interface.
func (v *AuthorBySlugAuthorsDocsAuthorAvatarMedia) GetHeight() *float64 { return v.Height }

// AuthorBySlugResponse is returned by AuthorBySlug on success.
type AuthorBySlugResponse struct {
	Authors *AuthorBySlugAuthors `json:"Authors"`
}

// GetAuthors returns AuthorBySlugResponse.Authors, and is useful for accessing the field via an interface.
func (v *AuthorBySlugResponse) GetAuthors() *AuthorBySlugAuthors { return v.Authors }

// AvailableLongNoteTagsAvailableTagsByMicroPostTypeTag includes the requested fields of the GraphQL type Tag.
type AvailableLongNoteTagsAvailableTagsByMicroPostTypeTag struct {
	Id    string  `json:"id"`
	Name  string  `json:"name"`
	Title *string `json:"title"`
}

// GetId returns AvailableLongNoteTagsAvailableTagsByMicroPostTypeTag.Id, and is useful for accessing the field via an interface.
func (v *AvailableLongNoteTagsAvailableTagsByMicroPostTypeTag) GetId() string { return v.Id }

// GetName returns AvailableLongNoteTagsAvailableTagsByMicroPostTypeTag.Name, and is useful for accessing the field via an interface.
func (v *AvailableLongNoteTagsAvailableTagsByMicroPostTypeTag) GetName() string { return v.Name }

// GetTitle returns AvailableLongNoteTagsAvailableTagsByMicroPostTypeTag.Title, and is useful for accessing the field via an interface.
func (v *AvailableLongNoteTagsAvailableTagsByMicroPostTypeTag) GetTitle() *string { return v.Title }

// AvailableLongNoteTagsResponse is returned by AvailableLongNoteTags on success.
type AvailableLongNoteTagsResponse struct {
	AvailableTagsByMicroPostType []AvailableLongNoteTagsAvailableTagsByMicroPostTypeTag `json:"availableTagsByMicroPostType"`
}

// GetAvailableTagsByMicroPostType returns AvailableLongNoteTagsResponse.AvailableTagsByMicroPostType, and is useful for accessing the field via an interface.
func (v *AvailableLongNoteTagsResponse) GetAvailableTagsByMicroPostType() []AvailableLongNoteTagsAvailableTagsByMicroPostTypeTag {
	return v.AvailableTagsByMicroPostType
}

// ListNotesByTagIDsMicro_posts includes the requested fields of the GraphQL type Micro_posts.
type ListNotesByTagIDsMicro_posts struct {
	TotalPages int                                          `json:"totalPages"`
	Docs       []ListNotesByTagIDsMicro_postsDocsMicro_post `json:"docs"`
}

// GetTotalPages returns ListNotesByTagIDsMicro_posts.TotalPages, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_posts) GetTotalPages() int { return v.TotalPages }

// GetDocs returns ListNotesByTagIDsMicro_posts.Docs, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_posts) GetDocs() []ListNotesByTagIDsMicro_postsDocsMicro_post {
	return v.Docs
}

// ListNotesByTagIDsMicro_postsDocsMicro_post includes the requested fields of the GraphQL type Micro_post.
type ListNotesByTagIDsMicro_postsDocsMicro_post struct {
	Id          string                                                         `json:"id"`
	Slug        *string                                                        `json:"slug"`
	Title       *string                                                        `json:"title"`
	Content     *string                                                        `json:"content"`
	PublishedAt *string                                                        `json:"publishedAt"`
	Authors     []ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthor      `json:"authors"`
	Tags        []ListNotesByTagIDsMicro_postsDocsMicro_postTagsTag            `json:"tags"`
	Attachment  *ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia     `json:"attachment"`
	Meta        *ListNotesByTagIDsMicro_postsDocsMicro_postMetaMicro_post_Meta `json:"meta"`
}

// GetId returns ListNotesByTagIDsMicro_postsDocsMicro_post.Id, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_post) GetId() string { return v.Id }

// GetSlug returns ListNotesByTagIDsMicro_postsDocsMicro_post.Slug, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_post) GetSlug() *string { return v.Slug }

// GetTitle returns ListNotesByTagIDsMicro_postsDocsMicro_post.Title, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_post) GetTitle() *string { return v.Title }

// GetContent returns ListNotesByTagIDsMicro_postsDocsMicro_post.Content, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_post) GetContent() *string { return v.Content }

// GetPublishedAt returns ListNotesByTagIDsMicro_postsDocsMicro_post.PublishedAt, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_post) GetPublishedAt() *string { return v.PublishedAt }

// GetAuthors returns ListNotesByTagIDsMicro_postsDocsMicro_post.Authors, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_post) GetAuthors() []ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthor {
	return v.Authors
}

// GetTags returns ListNotesByTagIDsMicro_postsDocsMicro_post.Tags, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_post) GetTags() []ListNotesByTagIDsMicro_postsDocsMicro_postTagsTag {
	return v.Tags
}

// GetAttachment returns ListNotesByTagIDsMicro_postsDocsMicro_post.Attachment, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_post) GetAttachment() *ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia {
	return v.Attachment
}

// GetMeta returns ListNotesByTagIDsMicro_postsDocsMicro_post.Meta, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_post) GetMeta() *ListNotesByTagIDsMicro_postsDocsMicro_postMetaMicro_post_Meta {
	return v.Meta
}

// ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia includes the requested fields of the GraphQL type Media.
type ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia struct {
	Url      *string  `json:"url"`
	Alt      *string  `json:"alt"`
	Width    *float64 `json:"width"`
	Height   *float64 `json:"height"`
	Filename *string  `json:"filename"`
	MimeType *string  `json:"mimeType"`
}

// GetUrl returns ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia.Url, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia) GetUrl() *string { return v.Url }

// GetAlt returns ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia.Alt, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia) GetAlt() *string { return v.Alt }

// GetWidth returns ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia.Width, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia) GetWidth() *float64 {
	return v.Width
}

// GetHeight returns ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia.Height, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia) GetHeight() *float64 {
	return v.Height
}

// GetFilename returns ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia.Filename, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia) GetFilename() *string {
	return v.Filename
}

// GetMimeType returns ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia.MimeType, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAttachmentMedia) GetMimeType() *string {
	return v.MimeType
}

// ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthor includes the requested fields of the GraphQL type Author.
type ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthor struct {
	Name   *string                                                             `json:"name"`
	Slug   string                                                              `json:"slug"`
	Bio    *string                                                             `json:"bio"`
	Avatar *ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia `json:"avatar"`
}

// GetName returns ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthor.Name, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthor) GetName() *string { return v.Name }

// GetSlug returns ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthor.Slug, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthor) GetSlug() string { return v.Slug }

// GetBio returns ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthor.Bio, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthor) GetBio() *string { return v.Bio }

// GetAvatar returns ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthor.Avatar, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthor) GetAvatar() *ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia {
	return v.Avatar
}

// ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia includes the requested fields of the GraphQL type Media.
type ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia struct {
	Url    *string  `json:"url"`
	Alt    *string  `json:"alt"`
	Width  *float64 `json:"width"`
	Height *float64 `json:"height"`
}

// GetUrl returns ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Url, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetUrl() *string {
	return v.Url
}

// GetAlt returns ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Alt, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetAlt() *string {
	return v.Alt
}

// GetWidth returns ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Width, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetWidth() *float64 {
	return v.Width
}

// GetHeight returns ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Height, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetHeight() *float64 {
	return v.Height
}

// ListNotesByTagIDsMicro_postsDocsMicro_postMetaMicro_post_Meta includes the requested fields of the GraphQL type Micro_post_Meta.
type ListNotesByTagIDsMicro_postsDocsMicro_postMetaMicro_post_Meta struct {
	Description *string `json:"description"`
}

// GetDescription returns ListNotesByTagIDsMicro_postsDocsMicro_postMetaMicro_post_Meta.Description, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postMetaMicro_post_Meta) GetDescription() *string {
	return v.Description
}

// ListNotesByTagIDsMicro_postsDocsMicro_postTagsTag includes the requested fields of the GraphQL type Tag.
type ListNotesByTagIDsMicro_postsDocsMicro_postTagsTag struct {
	Id    string  `json:"id"`
	Name  string  `json:"name"`
	Title *string `json:"title"`
}

// GetId returns ListNotesByTagIDsMicro_postsDocsMicro_postTagsTag.Id, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postTagsTag) GetId() string { return v.Id }

// GetName returns ListNotesByTagIDsMicro_postsDocsMicro_postTagsTag.Name, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postTagsTag) GetName() string { return v.Name }

// GetTitle returns ListNotesByTagIDsMicro_postsDocsMicro_postTagsTag.Title, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsMicro_postsDocsMicro_postTagsTag) GetTitle() *string { return v.Title }

// ListNotesByTagIDsResponse is returned by ListNotesByTagIDs on success.
type ListNotesByTagIDsResponse struct {
	Micro_posts *ListNotesByTagIDsMicro_posts `json:"Micro_posts"`
}

// GetMicro_posts returns ListNotesByTagIDsResponse.Micro_posts, and is useful for accessing the field via an interface.
func (v *ListNotesByTagIDsResponse) GetMicro_posts() *ListNotesByTagIDsMicro_posts {
	return v.Micro_posts
}

// ListNotesMicro_posts includes the requested fields of the GraphQL type Micro_posts.
type ListNotesMicro_posts struct {
	TotalPages int                                  `json:"totalPages"`
	Docs       []ListNotesMicro_postsDocsMicro_post `json:"docs"`
}

// GetTotalPages returns ListNotesMicro_posts.TotalPages, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_posts) GetTotalPages() int { return v.TotalPages }

// GetDocs returns ListNotesMicro_posts.Docs, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_posts) GetDocs() []ListNotesMicro_postsDocsMicro_post { return v.Docs }

// ListNotesMicro_postsDocsMicro_post includes the requested fields of the GraphQL type Micro_post.
type ListNotesMicro_postsDocsMicro_post struct {
	Id          string                                                 `json:"id"`
	Slug        *string                                                `json:"slug"`
	Title       *string                                                `json:"title"`
	Content     *string                                                `json:"content"`
	PublishedAt *string                                                `json:"publishedAt"`
	Authors     []ListNotesMicro_postsDocsMicro_postAuthorsAuthor      `json:"authors"`
	Tags        []ListNotesMicro_postsDocsMicro_postTagsTag            `json:"tags"`
	Attachment  *ListNotesMicro_postsDocsMicro_postAttachmentMedia     `json:"attachment"`
	Meta        *ListNotesMicro_postsDocsMicro_postMetaMicro_post_Meta `json:"meta"`
}

// GetId returns ListNotesMicro_postsDocsMicro_post.Id, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_post) GetId() string { return v.Id }

// GetSlug returns ListNotesMicro_postsDocsMicro_post.Slug, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_post) GetSlug() *string { return v.Slug }

// GetTitle returns ListNotesMicro_postsDocsMicro_post.Title, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_post) GetTitle() *string { return v.Title }

// GetContent returns ListNotesMicro_postsDocsMicro_post.Content, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_post) GetContent() *string { return v.Content }

// GetPublishedAt returns ListNotesMicro_postsDocsMicro_post.PublishedAt, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_post) GetPublishedAt() *string { return v.PublishedAt }

// GetAuthors returns ListNotesMicro_postsDocsMicro_post.Authors, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_post) GetAuthors() []ListNotesMicro_postsDocsMicro_postAuthorsAuthor {
	return v.Authors
}

// GetTags returns ListNotesMicro_postsDocsMicro_post.Tags, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_post) GetTags() []ListNotesMicro_postsDocsMicro_postTagsTag {
	return v.Tags
}

// GetAttachment returns ListNotesMicro_postsDocsMicro_post.Attachment, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_post) GetAttachment() *ListNotesMicro_postsDocsMicro_postAttachmentMedia {
	return v.Attachment
}

// GetMeta returns ListNotesMicro_postsDocsMicro_post.Meta, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_post) GetMeta() *ListNotesMicro_postsDocsMicro_postMetaMicro_post_Meta {
	return v.Meta
}

// ListNotesMicro_postsDocsMicro_postAttachmentMedia includes the requested fields of the GraphQL type Media.
type ListNotesMicro_postsDocsMicro_postAttachmentMedia struct {
	Url      *string  `json:"url"`
	Alt      *string  `json:"alt"`
	Width    *float64 `json:"width"`
	Height   *float64 `json:"height"`
	Filename *string  `json:"filename"`
	MimeType *string  `json:"mimeType"`
}

// GetUrl returns ListNotesMicro_postsDocsMicro_postAttachmentMedia.Url, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAttachmentMedia) GetUrl() *string { return v.Url }

// GetAlt returns ListNotesMicro_postsDocsMicro_postAttachmentMedia.Alt, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAttachmentMedia) GetAlt() *string { return v.Alt }

// GetWidth returns ListNotesMicro_postsDocsMicro_postAttachmentMedia.Width, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAttachmentMedia) GetWidth() *float64 { return v.Width }

// GetHeight returns ListNotesMicro_postsDocsMicro_postAttachmentMedia.Height, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAttachmentMedia) GetHeight() *float64 { return v.Height }

// GetFilename returns ListNotesMicro_postsDocsMicro_postAttachmentMedia.Filename, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAttachmentMedia) GetFilename() *string { return v.Filename }

// GetMimeType returns ListNotesMicro_postsDocsMicro_postAttachmentMedia.MimeType, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAttachmentMedia) GetMimeType() *string { return v.MimeType }

// ListNotesMicro_postsDocsMicro_postAuthorsAuthor includes the requested fields of the GraphQL type Author.
type ListNotesMicro_postsDocsMicro_postAuthorsAuthor struct {
	Name   *string                                                     `json:"name"`
	Slug   string                                                      `json:"slug"`
	Bio    *string                                                     `json:"bio"`
	Avatar *ListNotesMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia `json:"avatar"`
}

// GetName returns ListNotesMicro_postsDocsMicro_postAuthorsAuthor.Name, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAuthorsAuthor) GetName() *string { return v.Name }

// GetSlug returns ListNotesMicro_postsDocsMicro_postAuthorsAuthor.Slug, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAuthorsAuthor) GetSlug() string { return v.Slug }

// GetBio returns ListNotesMicro_postsDocsMicro_postAuthorsAuthor.Bio, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAuthorsAuthor) GetBio() *string { return v.Bio }

// GetAvatar returns ListNotesMicro_postsDocsMicro_postAuthorsAuthor.Avatar, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAuthorsAuthor) GetAvatar() *ListNotesMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia {
	return v.Avatar
}

// ListNotesMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia includes the requested fields of the GraphQL type Media.
type ListNotesMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia struct {
	Url    *string  `json:"url"`
	Alt    *string  `json:"alt"`
	Width  *float64 `json:"width"`
	Height *float64 `json:"height"`
}

// GetUrl returns ListNotesMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Url, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetUrl() *string { return v.Url }

// GetAlt returns ListNotesMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Alt, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetAlt() *string { return v.Alt }

// GetWidth returns ListNotesMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Width, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetWidth() *float64 {
	return v.Width
}

// GetHeight returns ListNotesMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Height, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetHeight() *float64 {
	return v.Height
}

// ListNotesMicro_postsDocsMicro_postMetaMicro_post_Meta includes the requested fields of the GraphQL type Micro_post_Meta.
type ListNotesMicro_postsDocsMicro_postMetaMicro_post_Meta struct {
	Description *string `json:"description"`
}

// GetDescription returns ListNotesMicro_postsDocsMicro_postMetaMicro_post_Meta.Description, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postMetaMicro_post_Meta) GetDescription() *string {
	return v.Description
}

// ListNotesMicro_postsDocsMicro_postTagsTag includes the requested fields of the GraphQL type Tag.
type ListNotesMicro_postsDocsMicro_postTagsTag struct {
	Id    string  `json:"id"`
	Name  string  `json:"name"`
	Title *string `json:"title"`
}

// GetId returns ListNotesMicro_postsDocsMicro_postTagsTag.Id, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postTagsTag) GetId() string { return v.Id }

// GetName returns ListNotesMicro_postsDocsMicro_postTagsTag.Name, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postTagsTag) GetName() string { return v.Name }

// GetTitle returns ListNotesMicro_postsDocsMicro_postTagsTag.Title, and is useful for accessing the field via an interface.
func (v *ListNotesMicro_postsDocsMicro_postTagsTag) GetTitle() *string { return v.Title }

// ListNotesResponse is returned by ListNotes on success.
type ListNotesResponse struct {
	Micro_posts *ListNotesMicro_posts `json:"Micro_posts"`
}

// GetMicro_posts returns ListNotesResponse.Micro_posts, and is useful for accessing the field via an interface.
func (v *ListNotesResponse) GetMicro_posts() *ListNotesMicro_posts { return v.Micro_posts }

// NoteBySlugMicro_posts includes the requested fields of the GraphQL type Micro_posts.
type NoteBySlugMicro_posts struct {
	Docs []NoteBySlugMicro_postsDocsMicro_post `json:"docs"`
}

// GetDocs returns NoteBySlugMicro_posts.Docs, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_posts) GetDocs() []NoteBySlugMicro_postsDocsMicro_post { return v.Docs }

// NoteBySlugMicro_postsDocsMicro_post includes the requested fields of the GraphQL type Micro_post.
type NoteBySlugMicro_postsDocsMicro_post struct {
	Id               string                                                                     `json:"id"`
	Slug             *string                                                                    `json:"slug"`
	Title            *string                                                                    `json:"title"`
	Content          *string                                                                    `json:"content"`
	PublishedAt      *string                                                                    `json:"publishedAt"`
	Authors          []NoteBySlugMicro_postsDocsMicro_postAuthorsAuthor                         `json:"authors"`
	Tags             []NoteBySlugMicro_postsDocsMicro_postTagsTag                               `json:"tags"`
	Attachment       *NoteBySlugMicro_postsDocsMicro_postAttachmentMedia                        `json:"attachment"`
	ExternalLinks    []NoteBySlugMicro_postsDocsMicro_postExternalLinksMicro_post_external_link `json:"externalLinks"`
	LinkedMicroPosts []NoteBySlugMicro_postsDocsMicro_postLinkedMicroPostsMicro_post            `json:"linkedMicroPosts"`
	Meta             *NoteBySlugMicro_postsDocsMicro_postMetaMicro_post_Meta                    `json:"meta"`
}

// GetId returns NoteBySlugMicro_postsDocsMicro_post.Id, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_post) GetId() string { return v.Id }

// GetSlug returns NoteBySlugMicro_postsDocsMicro_post.Slug, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_post) GetSlug() *string { return v.Slug }

// GetTitle returns NoteBySlugMicro_postsDocsMicro_post.Title, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_post) GetTitle() *string { return v.Title }

// GetContent returns NoteBySlugMicro_postsDocsMicro_post.Content, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_post) GetContent() *string { return v.Content }

// GetPublishedAt returns NoteBySlugMicro_postsDocsMicro_post.PublishedAt, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_post) GetPublishedAt() *string { return v.PublishedAt }

// GetAuthors returns NoteBySlugMicro_postsDocsMicro_post.Authors, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_post) GetAuthors() []NoteBySlugMicro_postsDocsMicro_postAuthorsAuthor {
	return v.Authors
}

// GetTags returns NoteBySlugMicro_postsDocsMicro_post.Tags, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_post) GetTags() []NoteBySlugMicro_postsDocsMicro_postTagsTag {
	return v.Tags
}

// GetAttachment returns NoteBySlugMicro_postsDocsMicro_post.Attachment, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_post) GetAttachment() *NoteBySlugMicro_postsDocsMicro_postAttachmentMedia {
	return v.Attachment
}

// GetExternalLinks returns NoteBySlugMicro_postsDocsMicro_post.ExternalLinks, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_post) GetExternalLinks() []NoteBySlugMicro_postsDocsMicro_postExternalLinksMicro_post_external_link {
	return v.ExternalLinks
}

// GetLinkedMicroPosts returns NoteBySlugMicro_postsDocsMicro_post.LinkedMicroPosts, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_post) GetLinkedMicroPosts() []NoteBySlugMicro_postsDocsMicro_postLinkedMicroPostsMicro_post {
	return v.LinkedMicroPosts
}

// GetMeta returns NoteBySlugMicro_postsDocsMicro_post.Meta, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_post) GetMeta() *NoteBySlugMicro_postsDocsMicro_postMetaMicro_post_Meta {
	return v.Meta
}

// NoteBySlugMicro_postsDocsMicro_postAttachmentMedia includes the requested fields of the GraphQL type Media.
type NoteBySlugMicro_postsDocsMicro_postAttachmentMedia struct {
	Url      *string  `json:"url"`
	Alt      *string  `json:"alt"`
	Width    *float64 `json:"width"`
	Height   *float64 `json:"height"`
	Filename *string  `json:"filename"`
	MimeType *string  `json:"mimeType"`
}

// GetUrl returns NoteBySlugMicro_postsDocsMicro_postAttachmentMedia.Url, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAttachmentMedia) GetUrl() *string { return v.Url }

// GetAlt returns NoteBySlugMicro_postsDocsMicro_postAttachmentMedia.Alt, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAttachmentMedia) GetAlt() *string { return v.Alt }

// GetWidth returns NoteBySlugMicro_postsDocsMicro_postAttachmentMedia.Width, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAttachmentMedia) GetWidth() *float64 { return v.Width }

// GetHeight returns NoteBySlugMicro_postsDocsMicro_postAttachmentMedia.Height, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAttachmentMedia) GetHeight() *float64 { return v.Height }

// GetFilename returns NoteBySlugMicro_postsDocsMicro_postAttachmentMedia.Filename, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAttachmentMedia) GetFilename() *string { return v.Filename }

// GetMimeType returns NoteBySlugMicro_postsDocsMicro_postAttachmentMedia.MimeType, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAttachmentMedia) GetMimeType() *string { return v.MimeType }

// NoteBySlugMicro_postsDocsMicro_postAuthorsAuthor includes the requested fields of the GraphQL type Author.
type NoteBySlugMicro_postsDocsMicro_postAuthorsAuthor struct {
	Name   *string                                                      `json:"name"`
	Slug   string                                                       `json:"slug"`
	Bio    *string                                                      `json:"bio"`
	Avatar *NoteBySlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia `json:"avatar"`
}

// GetName returns NoteBySlugMicro_postsDocsMicro_postAuthorsAuthor.Name, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAuthorsAuthor) GetName() *string { return v.Name }

// GetSlug returns NoteBySlugMicro_postsDocsMicro_postAuthorsAuthor.Slug, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAuthorsAuthor) GetSlug() string { return v.Slug }

// GetBio returns NoteBySlugMicro_postsDocsMicro_postAuthorsAuthor.Bio, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAuthorsAuthor) GetBio() *string { return v.Bio }

// GetAvatar returns NoteBySlugMicro_postsDocsMicro_postAuthorsAuthor.Avatar, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAuthorsAuthor) GetAvatar() *NoteBySlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia {
	return v.Avatar
}

// NoteBySlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia includes the requested fields of the GraphQL type Media.
type NoteBySlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia struct {
	Url    *string  `json:"url"`
	Alt    *string  `json:"alt"`
	Width  *float64 `json:"width"`
	Height *float64 `json:"height"`
}

// GetUrl returns NoteBySlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Url, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetUrl() *string { return v.Url }

// GetAlt returns NoteBySlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Alt, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetAlt() *string { return v.Alt }

// GetWidth returns NoteBySlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Width, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetWidth() *float64 {
	return v.Width
}

// GetHeight returns NoteBySlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Height, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetHeight() *float64 {
	return v.Height
}

// NoteBySlugMicro_postsDocsMicro_postExternalLinksMicro_post_external_link includes the requested fields of the GraphQL type Micro_post_external_link.
type NoteBySlugMicro_postsDocsMicro_postExternalLinksMicro_post_external_link struct {
	Id         string `json:"id"`
	Target_url string `json:"target_url"`
}

// GetId returns NoteBySlugMicro_postsDocsMicro_postExternalLinksMicro_post_external_link.Id, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postExternalLinksMicro_post_external_link) GetId() string {
	return v.Id
}

// GetTarget_url returns NoteBySlugMicro_postsDocsMicro_postExternalLinksMicro_post_external_link.Target_url, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postExternalLinksMicro_post_external_link) GetTarget_url() string {
	return v.Target_url
}

// NoteBySlugMicro_postsDocsMicro_postLinkedMicroPostsMicro_post includes the requested fields of the GraphQL type Micro_post.
type NoteBySlugMicro_postsDocsMicro_postLinkedMicroPostsMicro_post struct {
	Id   string  `json:"id"`
	Slug *string `json:"slug"`
}

// GetId returns NoteBySlugMicro_postsDocsMicro_postLinkedMicroPostsMicro_post.Id, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postLinkedMicroPostsMicro_post) GetId() string { return v.Id }

// GetSlug returns NoteBySlugMicro_postsDocsMicro_postLinkedMicroPostsMicro_post.Slug, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postLinkedMicroPostsMicro_post) GetSlug() *string {
	return v.Slug
}

// NoteBySlugMicro_postsDocsMicro_postMetaMicro_post_Meta includes the requested fields of the GraphQL type Micro_post_Meta.
type NoteBySlugMicro_postsDocsMicro_postMetaMicro_post_Meta struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
}

// GetTitle returns NoteBySlugMicro_postsDocsMicro_postMetaMicro_post_Meta.Title, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postMetaMicro_post_Meta) GetTitle() *string { return v.Title }

// GetDescription returns NoteBySlugMicro_postsDocsMicro_postMetaMicro_post_Meta.Description, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postMetaMicro_post_Meta) GetDescription() *string {
	return v.Description
}

// NoteBySlugMicro_postsDocsMicro_postTagsTag includes the requested fields of the GraphQL type Tag.
type NoteBySlugMicro_postsDocsMicro_postTagsTag struct {
	Id    string  `json:"id"`
	Name  string  `json:"name"`
	Title *string `json:"title"`
}

// GetId returns NoteBySlugMicro_postsDocsMicro_postTagsTag.Id, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postTagsTag) GetId() string { return v.Id }

// GetName returns NoteBySlugMicro_postsDocsMicro_postTagsTag.Name, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postTagsTag) GetName() string { return v.Name }

// GetTitle returns NoteBySlugMicro_postsDocsMicro_postTagsTag.Title, and is useful for accessing the field via an interface.
func (v *NoteBySlugMicro_postsDocsMicro_postTagsTag) GetTitle() *string { return v.Title }

// NoteBySlugResponse is returned by NoteBySlug on success.
type NoteBySlugResponse struct {
	Micro_posts *NoteBySlugMicro_posts `json:"Micro_posts"`
}

// GetMicro_posts returns NoteBySlugResponse.Micro_posts, and is useful for accessing the field via an interface.
func (v *NoteBySlugResponse) GetMicro_posts() *NoteBySlugMicro_posts { return v.Micro_posts }

// NotesByAuthorSlugMicro_posts includes the requested fields of the GraphQL type Micro_posts.
type NotesByAuthorSlugMicro_posts struct {
	TotalPages int                                          `json:"totalPages"`
	Docs       []NotesByAuthorSlugMicro_postsDocsMicro_post `json:"docs"`
}

// GetTotalPages returns NotesByAuthorSlugMicro_posts.TotalPages, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_posts) GetTotalPages() int { return v.TotalPages }

// GetDocs returns NotesByAuthorSlugMicro_posts.Docs, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_posts) GetDocs() []NotesByAuthorSlugMicro_postsDocsMicro_post {
	return v.Docs
}

// NotesByAuthorSlugMicro_postsDocsMicro_post includes the requested fields of the GraphQL type Micro_post.
type NotesByAuthorSlugMicro_postsDocsMicro_post struct {
	Id          string                                                         `json:"id"`
	Slug        *string                                                        `json:"slug"`
	Title       *string                                                        `json:"title"`
	Content     *string                                                        `json:"content"`
	PublishedAt *string                                                        `json:"publishedAt"`
	Authors     []NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthor      `json:"authors"`
	Tags        []NotesByAuthorSlugMicro_postsDocsMicro_postTagsTag            `json:"tags"`
	Attachment  *NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia     `json:"attachment"`
	Meta        *NotesByAuthorSlugMicro_postsDocsMicro_postMetaMicro_post_Meta `json:"meta"`
}

// GetId returns NotesByAuthorSlugMicro_postsDocsMicro_post.Id, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_post) GetId() string { return v.Id }

// GetSlug returns NotesByAuthorSlugMicro_postsDocsMicro_post.Slug, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_post) GetSlug() *string { return v.Slug }

// GetTitle returns NotesByAuthorSlugMicro_postsDocsMicro_post.Title, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_post) GetTitle() *string { return v.Title }

// GetContent returns NotesByAuthorSlugMicro_postsDocsMicro_post.Content, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_post) GetContent() *string { return v.Content }

// GetPublishedAt returns NotesByAuthorSlugMicro_postsDocsMicro_post.PublishedAt, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_post) GetPublishedAt() *string { return v.PublishedAt }

// GetAuthors returns NotesByAuthorSlugMicro_postsDocsMicro_post.Authors, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_post) GetAuthors() []NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthor {
	return v.Authors
}

// GetTags returns NotesByAuthorSlugMicro_postsDocsMicro_post.Tags, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_post) GetTags() []NotesByAuthorSlugMicro_postsDocsMicro_postTagsTag {
	return v.Tags
}

// GetAttachment returns NotesByAuthorSlugMicro_postsDocsMicro_post.Attachment, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_post) GetAttachment() *NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia {
	return v.Attachment
}

// GetMeta returns NotesByAuthorSlugMicro_postsDocsMicro_post.Meta, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_post) GetMeta() *NotesByAuthorSlugMicro_postsDocsMicro_postMetaMicro_post_Meta {
	return v.Meta
}

// NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia includes the requested fields of the GraphQL type Media.
type NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia struct {
	Url      *string  `json:"url"`
	Alt      *string  `json:"alt"`
	Width    *float64 `json:"width"`
	Height   *float64 `json:"height"`
	Filename *string  `json:"filename"`
	MimeType *string  `json:"mimeType"`
}

// GetUrl returns NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia.Url, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia) GetUrl() *string { return v.Url }

// GetAlt returns NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia.Alt, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia) GetAlt() *string { return v.Alt }

// GetWidth returns NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia.Width, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia) GetWidth() *float64 {
	return v.Width
}

// GetHeight returns NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia.Height, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia) GetHeight() *float64 {
	return v.Height
}

// GetFilename returns NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia.Filename, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia) GetFilename() *string {
	return v.Filename
}

// GetMimeType returns NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia.MimeType, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAttachmentMedia) GetMimeType() *string {
	return v.MimeType
}

// NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthor includes the requested fields of the GraphQL type Author.
type NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthor struct {
	Name   *string                                                             `json:"name"`
	Slug   string                                                              `json:"slug"`
	Bio    *string                                                             `json:"bio"`
	Avatar *NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia `json:"avatar"`
}

// GetName returns NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthor.Name, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthor) GetName() *string { return v.Name }

// GetSlug returns NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthor.Slug, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthor) GetSlug() string { return v.Slug }

// GetBio returns NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthor.Bio, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthor) GetBio() *string { return v.Bio }

// GetAvatar returns NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthor.Avatar, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthor) GetAvatar() *NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia {
	return v.Avatar
}

// NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia includes the requested fields of the GraphQL type Media.
type NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia struct {
	Url    *string  `json:"url"`
	Alt    *string  `json:"alt"`
	Width  *float64 `json:"width"`
	Height *float64 `json:"height"`
}

// GetUrl returns NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Url, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetUrl() *string {
	return v.Url
}

// GetAlt returns NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Alt, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetAlt() *string {
	return v.Alt
}

// GetWidth returns NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Width, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetWidth() *float64 {
	return v.Width
}

// GetHeight returns NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia.Height, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postAuthorsAuthorAvatarMedia) GetHeight() *float64 {
	return v.Height
}

// NotesByAuthorSlugMicro_postsDocsMicro_postMetaMicro_post_Meta includes the requested fields of the GraphQL type Micro_post_Meta.
type NotesByAuthorSlugMicro_postsDocsMicro_postMetaMicro_post_Meta struct {
	Description *string `json:"description"`
}

// GetDescription returns NotesByAuthorSlugMicro_postsDocsMicro_postMetaMicro_post_Meta.Description, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postMetaMicro_post_Meta) GetDescription() *string {
	return v.Description
}

// NotesByAuthorSlugMicro_postsDocsMicro_postTagsTag includes the requested fields of the GraphQL type Tag.
type NotesByAuthorSlugMicro_postsDocsMicro_postTagsTag struct {
	Id    string  `json:"id"`
	Name  string  `json:"name"`
	Title *string `json:"title"`
}

// GetId returns NotesByAuthorSlugMicro_postsDocsMicro_postTagsTag.Id, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postTagsTag) GetId() string { return v.Id }

// GetName returns NotesByAuthorSlugMicro_postsDocsMicro_postTagsTag.Name, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postTagsTag) GetName() string { return v.Name }

// GetTitle returns NotesByAuthorSlugMicro_postsDocsMicro_postTagsTag.Title, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugMicro_postsDocsMicro_postTagsTag) GetTitle() *string { return v.Title }

// NotesByAuthorSlugResponse is returned by NotesByAuthorSlug on success.
type NotesByAuthorSlugResponse struct {
	Micro_posts *NotesByAuthorSlugMicro_posts `json:"Micro_posts"`
}

// GetMicro_posts returns NotesByAuthorSlugResponse.Micro_posts, and is useful for accessing the field via an interface.
func (v *NotesByAuthorSlugResponse) GetMicro_posts() *NotesByAuthorSlugMicro_posts {
	return v.Micro_posts
}

// TagIDsByNamesResponse is returned by TagIDsByNames on success.
type TagIDsByNamesResponse struct {
	Tags *TagIDsByNamesTags `json:"Tags"`
}

// GetTags returns TagIDsByNamesResponse.Tags, and is useful for accessing the field via an interface.
func (v *TagIDsByNamesResponse) GetTags() *TagIDsByNamesTags { return v.Tags }

// TagIDsByNamesTags includes the requested fields of the GraphQL type Tags.
type TagIDsByNamesTags struct {
	Docs []TagIDsByNamesTagsDocsTag `json:"docs"`
}

// GetDocs returns TagIDsByNamesTags.Docs, and is useful for accessing the field via an interface.
func (v *TagIDsByNamesTags) GetDocs() []TagIDsByNamesTagsDocsTag { return v.Docs }

// TagIDsByNamesTagsDocsTag includes the requested fields of the GraphQL type Tag.
type TagIDsByNamesTagsDocsTag struct {
	Id    string  `json:"id"`
	Name  string  `json:"name"`
	Title *string `json:"title"`
}

// GetId returns TagIDsByNamesTagsDocsTag.Id, and is useful for accessing the field via an interface.
func (v *TagIDsByNamesTagsDocsTag) GetId() string { return v.Id }

// GetName returns TagIDsByNamesTagsDocsTag.Name, and is useful for accessing the field via an interface.
func (v *TagIDsByNamesTagsDocsTag) GetName() string { return v.Name }

// GetTitle returns TagIDsByNamesTagsDocsTag.Title, and is useful for accessing the field via an interface.
func (v *TagIDsByNamesTagsDocsTag) GetTitle() *string { return v.Title }

// __AuthorBySlugInput is used internally by genqlient
type __AuthorBySlugInput struct {
	Slug string `json:"slug"`
}

// GetSlug returns __AuthorBySlugInput.Slug, and is useful for accessing the field via an interface.
func (v *__AuthorBySlugInput) GetSlug() string { return v.Slug }

// __ListNotesByTagIDsInput is used internally by genqlient
type __ListNotesByTagIDsInput struct {
	Page   int      `json:"page"`
	Limit  int      `json:"limit"`
	TagIDs []string `json:"tagIDs"`
}

// GetPage returns __ListNotesByTagIDsInput.Page, and is useful for accessing the field via an interface.
func (v *__ListNotesByTagIDsInput) GetPage() int { return v.Page }

// GetLimit returns __ListNotesByTagIDsInput.Limit, and is useful for accessing the field via an interface.
func (v *__ListNotesByTagIDsInput) GetLimit() int { return v.Limit }

// GetTagIDs returns __ListNotesByTagIDsInput.TagIDs, and is useful for accessing the field via an interface.
func (v *__ListNotesByTagIDsInput) GetTagIDs() []string { return v.TagIDs }

// __ListNotesInput is used internally by genqlient
type __ListNotesInput struct {
	Page  int `json:"page"`
	Limit int `json:"limit"`
}

// GetPage returns __ListNotesInput.Page, and is useful for accessing the field via an interface.
func (v *__ListNotesInput) GetPage() int { return v.Page }

// GetLimit returns __ListNotesInput.Limit, and is useful for accessing the field via an interface.
func (v *__ListNotesInput) GetLimit() int { return v.Limit }

// __NoteBySlugInput is used internally by genqlient
type __NoteBySlugInput struct {
	Slug string `json:"slug"`
}

// GetSlug returns __NoteBySlugInput.Slug, and is useful for accessing the field via an interface.
func (v *__NoteBySlugInput) GetSlug() string { return v.Slug }

// __NotesByAuthorSlugInput is used internally by genqlient
type __NotesByAuthorSlugInput struct {
	Slug  string `json:"slug"`
	Page  int    `json:"page"`
	Limit int    `json:"limit"`
}

// GetSlug returns __NotesByAuthorSlugInput.Slug, and is useful for accessing the field via an interface.
func (v *__NotesByAuthorSlugInput) GetSlug() string { return v.Slug }

// GetPage returns __NotesByAuthorSlugInput.Page, and is useful for accessing the field via an interface.
func (v *__NotesByAuthorSlugInput) GetPage() int { return v.Page }

// GetLimit returns __NotesByAuthorSlugInput.Limit, and is useful for accessing the field via an interface.
func (v *__NotesByAuthorSlugInput) GetLimit() int { return v.Limit }

// __TagIDsByNamesInput is used internally by genqlient
type __TagIDsByNamesInput struct {
	TagNames []string `json:"tagNames"`
}

// GetTagNames returns __TagIDsByNamesInput.TagNames, and is useful for accessing the field via an interface.
func (v *__TagIDsByNamesInput) GetTagNames() []string { return v.TagNames }

// The query executed by AuthorBySlug.
const AuthorBySlug_Operation = `
query AuthorBySlug ($slug: String!) {
	Authors(where: {slug:{equals:$slug}}, limit: 1) {
		docs {
			id
			name
			slug
			bio
			avatar {
				url
				alt
				width
				height
			}
		}
	}
}
`

func AuthorBySlug(
	ctx_ context.Context,
	client_ graphql.Client,
	slug string,
) (data_ *AuthorBySlugResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AuthorBySlug",
		Query:  AuthorBySlug_Operation,
		Variables: &__AuthorBySlugInput{
			Slug: slug,
		},
	}

	data_ = &AuthorBySlugResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by AvailableLongNoteTags.
const AvailableLongNoteTags_Operation = `
query AvailableLongNoteTags {
	availableTagsByMicroPostType(postType: "long") {
		id
		name
		title
	}
}
`

func AvailableLongNoteTags(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *AvailableLongNoteTagsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "AvailableLongNoteTags",
		Query:  AvailableLongNoteTags_Operation,
	}

	data_ = &AvailableLongNoteTagsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListNotes.
const ListNotes_Operation = `
query ListNotes ($page: Int!, $limit: Int!) {
	Micro_posts(page: $page, limit: $limit, sort: "-publishedAt", where: {_status:{equals:published},post_type:{equals:long}}) {
		totalPages
		docs {
			id
			slug
			title
			content
			publishedAt
			authors {
				name
				slug
				bio
				avatar {
					url
					alt
					width
					height
				}
			}
			tags {
				id
				name
				title
			}
			attachment {
				url
				alt
				width
				height
				filename
				mimeType
			}
			meta {
				description
			}
		}
	}
}
`

func ListNotes(
	ctx_ context.Context,
	client_ graphql.Client,
	page int,
	limit int,
) (data_ *ListNotesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListNotes",
		Query:  ListNotes_Operation,
		Variables: &__ListNotesInput{
			Page:  page,
			Limit: limit,
		},
	}

	data_ = &ListNotesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ListNotesByTagIDs.
const ListNotesByTagIDs_Operation = `
query ListNotesByTagIDs ($page: Int!, $limit: Int!, $tagIDs: [JSON!]!) {
	Micro_posts(page: $page, limit: $limit, sort: "-publishedAt", where: {_status:{equals:published},post_type:{equals:long},tags:{in:$tagIDs}}) {
		totalPages
		docs {
			id
			slug
			title
			content
			publishedAt
			authors {
				name
				slug
				bio
				avatar {
					url
					alt
					width
					height
				}
			}
			tags {
				id
				name
				title
			}
			attachment {
				url
				alt
				width
				height
				filename
				mimeType
			}
			meta {
				description
			}
		}
	}
}
`

func ListNotesByTagIDs(
	ctx_ context.Context,
	client_ graphql.Client,
	page int,
	limit int,
	tagIDs []string,
) (data_ *ListNotesByTagIDsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ListNotesByTagIDs",
		Query:  ListNotesByTagIDs_Operation,
		Variables: &__ListNotesByTagIDsInput{
			Page:   page,
			Limit:  limit,
			TagIDs: tagIDs,
		},
	}

	data_ = &ListNotesByTagIDsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by NoteBySlug.
const NoteBySlug_Operation = `
query NoteBySlug ($slug: String!) {
	Micro_posts(limit: 1, where: {_status:{equals:published},slug:{equals:$slug},post_type:{equals:long}}) {
		docs {
			id
			slug
			title
			content
			publishedAt
			authors {
				name
				slug
				bio
				avatar {
					url
					alt
					width
					height
				}
			}
			tags {
				id
				name
				title
			}
			attachment {
				url
				alt
				width
				height
				filename
				mimeType
			}
			externalLinks {
				id
				target_url
			}
			linkedMicroPosts {
				id
				slug
			}
			meta {
				title
				description
			}
		}
	}
}
`

func NoteBySlug(
	ctx_ context.Context,
	client_ graphql.Client,
	slug string,
) (data_ *NoteBySlugResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "NoteBySlug",
		Query:  NoteBySlug_Operation,
		Variables: &__NoteBySlugInput{
			Slug: slug,
		},
	}

	data_ = &NoteBySlugResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by NotesByAuthorSlug.
const NotesByAuthorSlug_Operation = `
query NotesByAuthorSlug ($slug: String!, $page: Int!, $limit: Int!) {
	Micro_posts(page: $page, limit: $limit, sort: "-publishedAt", where: {_status:{equals:published},post_type:{equals:long},authorSlug:{equals:$slug}}) {
		totalPages
		docs {
			id
			slug
			title
			content
			publishedAt
			authors {
				name
				slug
				bio
				avatar {
					url
					alt
					width
					height
				}
			}
			tags {
				id
				name
				title
			}
			attachment {
				url
				alt
				width
				height
				filename
				mimeType
			}
			meta {
				description
			}
		}
	}
}
`

func NotesByAuthorSlug(
	ctx_ context.Context,
	client_ graphql.Client,
	slug string,
	page int,
	limit int,
) (data_ *NotesByAuthorSlugResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "NotesByAuthorSlug",
		Query:  NotesByAuthorSlug_Operation,
		Variables: &__NotesByAuthorSlugInput{
			Slug:  slug,
			Page:  page,
			Limit: limit,
		},
	}

	data_ = &NotesByAuthorSlugResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by TagIDsByNames.
const TagIDsByNames_Operation = `
query TagIDsByNames ($tagNames: [String!]!) {
	Tags(where: {name:{in:$tagNames}}) {
		docs {
			id
			name
			title
		}
	}
}
`

func TagIDsByNames(
	ctx_ context.Context,
	client_ graphql.Client,
	tagNames []string,
) (data_ *TagIDsByNamesResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "TagIDsByNames",
		Query:  TagIDsByNames_Operation,
		Variables: &__TagIDsByNamesInput{
			TagNames: tagNames,
		},
	}

	data_ = &TagIDsByNamesResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
