// Code generated by cmd/approutegen. DO NOT EDIT.
package routes_gen

import (
	"blog/framework"
	"blog/framework/router"
	"blog/internal/web/appcore"
	r_layout_author_param_slug "blog/internal/web/routes_gen/r_layout_author_param_slug"
	r_layout_root "blog/internal/web/routes_gen/r_layout_root"
	r_page_author_param_slug "blog/internal/web/routes_gen/r_page_author_param_slug"
	r_page_note_param_slug "blog/internal/web/routes_gen/r_page_note_param_slug"
	r_page_notes "blog/internal/web/routes_gen/r_page_notes"
	"github.com/a-h/templ"
	"strings"
)

func Handlers() []framework.RouteHandler[*appcore.Context] {
	return []framework.RouteHandler[*appcore.Context]{
		framework.PageAndLiveRouteHandler[*appcore.Context, framework.SlugParams, appcore.AuthorPageView, appcore.AuthorSignalState]{
			Page: framework.PageModule[*appcore.Context, framework.SlugParams, appcore.AuthorPageView]{
				Pattern:     "/author/[slug]",
				ParseParams: parseAuthorSlugParams,
				Load:        appcore.LoadAuthorPage,
				Render:      r_page_author_param_slug.Page,
				Layouts: []framework.LayoutRenderer[appcore.AuthorPageView]{
					wrapAuthorSlugWithRootLayout,
					wrapAuthorSlugWithAuthorSlugLayout,
				},
			},
			Live: framework.LiveModule[*appcore.Context, framework.SlugParams, appcore.AuthorPageView, appcore.AuthorSignalState]{
				Pattern:           "/author/[slug]/live",
				ParseParams:       parseAuthorSlugLiveParams,
				ParseState:        appcore.ParseAuthorLiveState,
				Load:              appcore.LoadAuthorLivePage,
				Render:            r_page_author_param_slug.Page,
				SelectorID:        "author-content",
				BadRequestMessage: "invalid datastar signal payload",
			},
		},
		framework.PageOnlyRouteHandler[*appcore.Context, framework.SlugParams, appcore.NotePageView]{
			Page: framework.PageModule[*appcore.Context, framework.SlugParams, appcore.NotePageView]{
				Pattern:     "/note/[slug]",
				ParseParams: parseNoteSlugParams,
				Load:        appcore.LoadNotePage,
				Render:      r_page_note_param_slug.Page,
				Layouts: []framework.LayoutRenderer[appcore.NotePageView]{
					wrapNoteSlugWithRootLayout,
				},
			},
		},
		framework.PageAndLiveRouteHandler[*appcore.Context, framework.EmptyParams, appcore.NotesPageView, appcore.NotesSignalState]{
			Page: framework.PageModule[*appcore.Context, framework.EmptyParams, appcore.NotesPageView]{
				Pattern:     "/notes",
				ParseParams: parseNotesParams,
				Load:        appcore.LoadNotesPage,
				Render:      r_page_notes.Page,
				Layouts: []framework.LayoutRenderer[appcore.NotesPageView]{
					wrapNotesWithRootLayout,
				},
			},
			Live: framework.LiveModule[*appcore.Context, framework.EmptyParams, appcore.NotesPageView, appcore.NotesSignalState]{
				Pattern:           "/notes/live",
				ParseParams:       parseNotesLiveParams,
				ParseState:        appcore.ParseNotesLiveState,
				Load:              appcore.LoadNotesLivePage,
				Render:            r_page_notes.Page,
				SelectorID:        "notes-content",
				BadRequestMessage: "invalid datastar signal payload",
			},
		},
	}
}

func parseAuthorSlugLiveParams(requestPath string) (framework.SlugParams, bool) {
	params, ok := router.MatchPathPattern("/author/[slug]/live", requestPath)
	if !ok {
		return framework.SlugParams{}, false
	}
	slug := strings.TrimSpace(params["slug"])
	if !router.IsValidSlug(slug) {
		return framework.SlugParams{}, false
	}
	return framework.SlugParams{Slug: slug}, true
}

func parseAuthorSlugParams(requestPath string) (framework.SlugParams, bool) {
	params, ok := router.MatchPathPattern("/author/[slug]", requestPath)
	if !ok {
		return framework.SlugParams{}, false
	}
	slug := strings.TrimSpace(params["slug"])
	if !router.IsValidSlug(slug) {
		return framework.SlugParams{}, false
	}
	return framework.SlugParams{Slug: slug}, true
}

func parseNoteSlugParams(requestPath string) (framework.SlugParams, bool) {
	params, ok := router.MatchPathPattern("/note/[slug]", requestPath)
	if !ok {
		return framework.SlugParams{}, false
	}
	slug := strings.TrimSpace(params["slug"])
	if !router.IsValidSlug(slug) {
		return framework.SlugParams{}, false
	}
	return framework.SlugParams{Slug: slug}, true
}

func parseNotesLiveParams(requestPath string) (framework.EmptyParams, bool) {
	_, ok := router.MatchPathPattern("/notes/live", requestPath)
	if !ok {
		return framework.EmptyParams{}, false
	}
	return framework.EmptyParams{}, true
}

func parseNotesParams(requestPath string) (framework.EmptyParams, bool) {
	_, ok := router.MatchPathPattern("/notes", requestPath)
	if !ok {
		return framework.EmptyParams{}, false
	}
	return framework.EmptyParams{}, true
}

func wrapAuthorSlugWithAuthorSlugLayout(view appcore.AuthorPageView, child templ.Component) templ.Component {
	return r_layout_author_param_slug.Layout(view, child)
}

func wrapAuthorSlugWithRootLayout(view appcore.AuthorPageView, child templ.Component) templ.Component {
	return r_layout_root.Layout(view, child)
}

func wrapNoteSlugWithRootLayout(view appcore.NotePageView, child templ.Component) templ.Component {
	return r_layout_root.Layout(view, child)
}

func wrapNotesWithRootLayout(view appcore.NotesPageView, child templ.Component) templ.Component {
	return r_layout_root.Layout(view, child)
}
