// Code generated by cmd/approutegen. DO NOT EDIT.
package resolvers

import (
	"blog/web/view"
	"context"
	"github.com/RevoTale/no-js/framework"
	"github.com/RevoTale/no-js/framework/metagen"
	"net/http"
)

type RootParams struct {
}

type AuthorParamSlugParams struct {
	Slug string
}

type ChannelsParams struct {
}

type MicroTalesParams struct {
}

type NoteParamSlugParams struct {
	Slug string
}

type TagParamSlugParams struct {
	Slug string
}

type TalesParams struct {
}

type RouteResolver interface {
	MetaGenRootLayout(meta framework.MetaContext[*runtime.Context]) (metagen.Metadata, error)
	MetaGenAuthorParamSlugLayout(meta framework.MetaContext[*runtime.Context], params AuthorParamSlugParams) (metagen.Metadata, error)
	MetaGenRootPage(meta framework.MetaContext[*runtime.Context], params RootParams) (metagen.Metadata, error)
	MetaGenAuthorParamSlugPage(meta framework.MetaContext[*runtime.Context], params AuthorParamSlugParams) (metagen.Metadata, error)
	MetaGenChannelsPage(meta framework.MetaContext[*runtime.Context], params ChannelsParams) (metagen.Metadata, error)
	MetaGenMicroTalesPage(meta framework.MetaContext[*runtime.Context], params MicroTalesParams) (metagen.Metadata, error)
	MetaGenNoteParamSlugPage(meta framework.MetaContext[*runtime.Context], params NoteParamSlugParams) (metagen.Metadata, error)
	MetaGenTagParamSlugPage(meta framework.MetaContext[*runtime.Context], params TagParamSlugParams) (metagen.Metadata, error)
	MetaGenTalesPage(meta framework.MetaContext[*runtime.Context], params TalesParams) (metagen.Metadata, error)
	ResolveRootPage(ctx context.Context, appCtx *runtime.Context, r *http.Request, params RootParams) (runtime.NotesPageView, error)
	ResolveAuthorParamSlugPage(ctx context.Context, appCtx *runtime.Context, r *http.Request, params AuthorParamSlugParams) (runtime.AuthorPageView, error)
	ResolveChannelsPage(ctx context.Context, appCtx *runtime.Context, r *http.Request, params ChannelsParams) (runtime.NotesPageView, error)
	ResolveMicroTalesPage(ctx context.Context, appCtx *runtime.Context, r *http.Request, params MicroTalesParams) (runtime.NotesPageView, error)
	ResolveNoteParamSlugPage(ctx context.Context, appCtx *runtime.Context, r *http.Request, params NoteParamSlugParams) (runtime.NotePageView, error)
	ResolveTagParamSlugPage(ctx context.Context, appCtx *runtime.Context, r *http.Request, params TagParamSlugParams) (runtime.NotesPageView, error)
	ResolveTalesPage(ctx context.Context, appCtx *runtime.Context, r *http.Request, params TalesParams) (runtime.NotesPageView, error)
}

type Resolver struct{}

var _ RouteResolver = (*Resolver)(nil)
