// Code generated by framework/cmd/approutegen. DO NOT EDIT.
package resolvers

import (
	"blog/internal/web/appcore"
	"context"
	"net/http"
)

type RootParams struct {
}

type AuthorParamSlugParams struct {
	Slug string
}

type ChannelsParams struct {
}

type MicroTalesParams struct {
}

type NoteParamSlugParams struct {
	Slug string
}

type TagParamSlugParams struct {
	Slug string
}

type TalesParams struct {
}

type RouteResolver interface {
	ResolveRootPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params RootParams) (appcore.NotesPageView, error)
	ResolveAuthorParamSlugPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params AuthorParamSlugParams) (appcore.AuthorPageView, error)
	ParseAuthorParamSlugLiveState(r *http.Request) (appcore.AuthorSignalState, error)
	ResolveAuthorParamSlugLive(ctx context.Context, appCtx *appcore.Context, r *http.Request, params AuthorParamSlugParams, state appcore.AuthorSignalState) (appcore.AuthorPageView, error)
	ResolveChannelsPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params ChannelsParams) (appcore.NotesPageView, error)
	ResolveMicroTalesPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params MicroTalesParams) (appcore.NotesPageView, error)
	ResolveNoteParamSlugPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params NoteParamSlugParams) (appcore.NotePageView, error)
	ResolveTagParamSlugPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params TagParamSlugParams) (appcore.NotesPageView, error)
	ResolveTalesPage(ctx context.Context, appCtx *appcore.Context, r *http.Request, params TalesParams) (appcore.NotesPageView, error)
}

type Resolver struct{}

var _ RouteResolver = (*Resolver)(nil)
